<a href="https://colab.research.google.com/github/josephnagel1/MATH311_linear_algebra_projects/blob/main/Gram_Schmidt_Orthonormalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load libraries

In [27]:
import numpy as np

# Finding orthonormal vectors using the Gram-Schmidt Orthonormalization Process

Starting vectors:

In [28]:
r1 = np.array([3, 0, 3, 0])

r2 = np.array([3, 2, 3, 3])

r3 = np.array([-7, -4, -5, -6])

r4 = np.array([-7, -3, -11, 2])

Find
 - $\vec t_1 = \vec r_1$
 - $\hat u_1 = \frac{\vec t_1}{\left| \vec t_1 \right|}$

In [29]:
t1 = r1

u1 = t1/(np.sqrt(t1.dot(t1)))

In [30]:
u1.round(2)

array([0.71, 0.  , 0.71, 0.  ])

Find
 - $\vec t_2 = \vec r_2 - (\hat u_1 \cdot \vec r_2) \hat u_1$
 - $\hat u_2 = \frac{\vec t_2}{\left| \vec t_2 \right|}$

In [31]:
t2 = r2 - (u1.dot(r2))*u1

u2 = t2/(np.sqrt(t2.dot(t2)))

In [32]:
u2.round(2)

array([-0.  ,  0.55, -0.  ,  0.83])

Find
 - $\vec t_3 = \vec r_3 - (\hat u_1 \cdot \vec r_3) \hat u_1 - (\hat u_2 \cdot \vec r_3) \hat u_2$
 - $\hat u_3 = \frac{\vec t_3}{\left| \vec t_3 \right|}$

In [33]:
t3 = (r3 - (u1.dot(r3)*u1) - (u2.dot(r3)*u2))

u3 = t3/(np.sqrt(t3.dot(t3)))

In [34]:
u3.round(2)

array([-0.71, -0.  ,  0.71, -0.  ])

Find
 - $\vec t_4 = \vec r_4 - (\hat u_1 \cdot \vec r_4) \hat u_1 - (\hat u_2 \cdot \vec r_4) \hat u_2 - (\hat u_3 \cdot \vec r_4) \hat u_3$
 - $\hat u_4 = \frac{\vec t_4}{\left| \vec t_4 \right|}$

In [35]:
t4 = r4 - (u1.dot(r4)*u1) - (u2.dot(r4)*u2) - (u3.dot(r4)*u3)

u4 = t4/(np.sqrt(t4.dot(t4)))

In [36]:
u4.round(2)

array([ 0.  , -0.83,  0.  ,  0.55])